### PR TITLE
评论

### PR DESCRIPTION
**Pull request by zhangweilst**

### CODE REVIEW

**Review by jcao-ai — COMMENTED** [review]
@zhangweilst 同意

**Comment by ecnelises** [comment]
你会去使用一个绑定手机号登录之后才能使用的 Google 吗？

Would you like to use a so-called Google requiring logging in with a phone number associated with your ID?

**Comment by uiHdynpOa** [comment]
@ithinco 

I don't know whether Google is aware of this or not, but the Dragonfly project is basically Google donating a **weapon of massive censorship** to PRC.

Sure, the people would get one more search engine, but the government would get one more **major channel for propaganda** too, are you sure it's beneficial for "the rest"?

The political atmosphere in China contributed a huge amount (if not all) of the chaos in Chinese IT industry. Have you seen the statement **"To comply with local law, some search results are removed"**? Can you find that specific "law" clause in China? Do you know **why** there isn't a specific one? A company can only pursuit quick money under these "bendable" law and turn into **another Baidu**, if it is to survive.

Do you think Google can, or will, get itself involved in a political war? No, I don't think so. Google is **already complying** with the Chinese government by starting Dragonfly. Google **can not** and **will not** change the political atmosphere in China, but it's deemed to be changed by the Chinese government.

The Chinese politics is a plague. **Please don't get infected, Google.**

Edit: I'm a Chinese, and this is a dispensable account for this political talk. And yes, I'm afraid that by complying with requirements from the Chinese government, Google would some day turn me in for simple comments like this one.

**Comment by ithinco** [comment]
You can publish your reply on the comment section of HackerNews or Medium, or publish it separately.

**Comment by uiHdynpOa** [comment]
@ithinco Yeah yeah HackerNews. Whatever. Have you actually read the comments there? Are you ashamed of yourself yet?

**Comment by 0polar** [comment]
通篇基于一个假设：【中国特色版 Google (the Dragonfly)】=【原版 Google】
但这显然是不成立的

This article assume [Chinese special Google (the Dragonfly)] = [original Google]
But this is obviously false.

**Pull request closed without merging**
